"use strict";

module.exports = {
  SUCCESS_CODE: 200,
  ALLREADY_EXIST: 409,
  ERROR_CODE: 400,
  AUTH_CODE: 401,



  //LOGIN LOGS
  DEFAULT_PASSWORD: "123456",

  WELCOME_USER_TEMPLATE_CODE: "welcome",
  VERIFICATION_USER_TEMPLATE_CODE: "verification",
  RESET_TEMPLATE_CODE: "reset",
  INVITE_COMP_TEMPLATE_CODE_PUBLIC: "inviteCompPublic",
  INVITE_COMP_TEMPLATE_CODE_PRIVATE: "inviteCompPrivate",
  FORGOT_PASSWORD_CODE: "forgot",
  CHANGE_PASSWORD_CODE: "changepassword",
  SIGNIN_SUCCESS: "Login successfully",
  NEW_USER_SAVE_SUCCESS:
    "You registered successfully. Please check your otp and verify.",
  NEW_ROLE_SAVE_SUCCESS: "New Role added successfully.",
  NEW_SPORT_SAVE_SUCCESS: "New Sport added successsfully",
  NEW_ROUND_SAVE_SUCCESS: "New Round added successsfully",
  NEW_CATEGORY_SAVE_SUCCESS: "New Category added successfully.",
  NEW_TEAM_SAVE_SUCCESS: "New Team added successfully",
  GAME_UPDATED_SUCCESS: "Game detail updated successfully",
  ROUND_UPDATED_SUCCESS: "Round detail updated successfully",
  // GAME_UPDATED_UNSUCCESS:'Game detail was unable to update',
  NEW_SUBCATEGORY_SAVE_SUCCESS: "New subcategory added successfully",
  SOMETHING_WENT_WRONG: "Something went wrong",
  EXT_ERROR: "Please check the extension of file",
  DATA_NOT_FOUND: "Data not found",
  DATA_FETCH_SUCCESS: "Data fetched successfully",
  INVALID_LOGIN_DETAILS: "Please enter correct mobile no. and password.",
  LOGIN_REQUIRED_FIELDS: "Login credentials required",
  UNAUTHORIZE_USER: "User is unauthorised",
  EMAIL_NOT_VERIFIED: "Please verify your mobile no.",
  INVALID_PASSWORD: "Invalid Password",
  INVALID_TOKEN: "Invalid Token",
  ADD_SUCCESS: "Successfully added",
  INVITE_SUCCESS: "Successfully invited",
  STATUS_CHANGE: "Status changed successfully",
  EMAIL_ALREADY_REGISTERED: "Email already registered. Please try another one",
  ROLE_EXIST: "Role already exist",
  TEAM_EXIST: "Team already exist",
  SPORT_EXIST: "Sport already exist",
  BONUS_EXIST: "Bonus already exist",
  ROUND_EXIST: "Round already exist",
  saveTo_TILE_EXIST: "Save To Title already exists",
  COMPETITION_EXIST: "Competition name already exist",
  COMPETITION_NOT_EXIST: "Competition name not exist",
  GAME_STATE_UPDATED: "Game state updated successfully",
  GAME_UPDATED_UNSUCCESS: "Falied to update",
  DELETE_GAME_SUCCESS: "game deleted successfully",
  GAME_EXIST: "Game already exist",
  CATEGORY_EXIST: "Category already exist",
  SUBCATEGORY_EXIST: "Subcategory already exist",
  PASSWORD_RESET: "Password Reset successfully",
  PASSWORD_CHANGE: "Password changed successfully",
  SUCCESS_UPLOAD: "Successfully Uploaded",
  UPLOAD_SAVED: "Uploaded data saved successfully",
  EXT_ERROR: "Error while uploading",
  UPLOAD_FAILED: "Upload failed",
  NEW_COMP_SAVE_SUCCESS: "New Competition added successfully",
  COMP_UPDATED_SUCCESS: "Competition privacy status changed successfully",
  COMP_UPDATED_UNSUCCESS: "Failed to change the privacy status",
  COMP_JOIN_SUCCESS: "You have successfully joined the competition",
  PRODUCT_LIST_UNSUCCESS: "Oops! Product list was not fetched",
  DELETE_ROUND_SUCCESS: "Round deleted successfully",
  EMAILTEMPLATE_SAVE_SUCCESS: "Email template saved successfully",
  NEW_BONUS_SAVE_SUCCESS: "Bonus saved successfully",
  EMAIL_VERIFIED: "Email verified successfully",
  INTERNAL_ERROR: "Error occured",
  VERIFICATION_FAILED: "Verification failed. PLease try again later.",
  PASSWORD_ERROR: "Your old password is not correct.",
  TOKEN_ERROR: "Token not found!",
  INVALID_TOKEN: "Invalid Token!",
  NOT_PROPER_DATA: "Not proper data!",
  USER_UPDATED_SUCCESS: "User data updated successfully",
  USER_UPDATED_UNSUCCESS: "User data was unable to be updated",
  LINK_SENT: "Link sent successfully on mail to reset password",
  OTP_SENT: "OTP sent successfully on mail to reset password",
  DELETE_USER_SUCCESS: "User deleted successfully",
  DELETE_TEAM_SUCCESS: "Team deleted successfully",
  USER_NOT_EXIST: "User does not exist",
  DATA_FETCHED: "Data fetched successfully",
  GAME_DATA_ADDED: "Game data added successfully",
  PROFILE_PIC_SAVE: "Profile pic saved",
  ERROR_OCCURED: "Error Occured!",
  DELETE_CATEGORY_SUCCESS: "Category deleted successfully",
  DELETE_SPORT_SUCCESS: "Sport deleted successfully",
  SPORT_UPDATED_SUCCESS: "Sportdetail updated successfully",
  SPORT_UPDATED_UNSUCCESS: "Unable to update sportdetail",
  TEAM_UPDATED_SUCCESS: "Teamdetail updated successfully",
  TEAM_UPDATED_UNSUCCESS: "Unable to update teamdetail",
  DELETE_PRODUCT_SUCCESS: "Delete product successfully",
  NOTIFICATION_SAVED: "Notification data saved",
  ASSOCIATED_CATEGORY: "Category associated with product",
  SENT_VERIFICATION_LINK: "Verification link sent to your mail",
  LOGO_IMG_PATH: "./app/uploads/teamlogo/",
  ASTROLOGER_IMG_PATH: "./api/uploads/astrologer/profile/",
  USER_IMG_PATH: "./api/uploads/user/profile/",
  PROFILE_IMG_PATH: "./app/uploads/profile/",
  CATEGORY_IMG_PATH: "./api/uploads/category/",
  BRAND_IMG_PATH: "./api/uploads/brand/",
  ARTIST_IMG_PATH: "./api/uploads/artist/",
  POSTER_IMG_PATH: "./api/uploads/poster/",
  SONG_IMG_PATH: "./api/uploads/song/",
  IMAGE_IMG_PATH: "./api/uploads/image/",
  CHAT_IMG_PATH: "./app/uploads/chat/",
  COVER_IMG_PATH: "./app/uploads/cover/",
  CONTEST_IMG_PATH: "./api/uploads/contest/",
  ROUND_IMG_PATH: "./api/uploads/round/",
  ROUND_QUESTION_FILE_PATH: "./api/uploads/roundQuestion/",
  DELETE_BONUS_SUCCESS: "Bonus deleted successfully",
  USER_NOT_AVAILABLE: "This account has not been setup on Murabbo.",
  SAVE_TO_NOT_AVAILABLE: "save to is not available",
  CONTEST_NOT_AVAILABLE: "contest is not available",
  ROUND_NOT_AVAILABLE: "round is not available",
  ROUND_QUESTION_NOT_AVAILABLE: "round question is not available",
  CATEGORY_NOT_AVAILABLE: "category is not available",
  BRAND_NOT_AVAILABLE: "brand is not available",

  DATA_SAVE_SUCCESS: "Data saved successfully",
  DATA_SAVE_USUCCESS: "Failed to save",
  DATA_UPDATE_SUCCESS: "Data updated successfully",
  DATA_UPDATE_UNSUCCESS: "Failed to update",
  DATA_EXIST: "Data already exist",
  DELETE_DATA_SUCCESS: "Data deleted successfully",
  PARAMETER_MISSING_ERROR:
    "There are one or more parameters missing in the supplied request!",

  PROJECTION_MISSING_ERROR:
    "Projection parameters missing in the supplied request!",

  SAVE_TIPPING_SUCCESS: "The bonus was played",

  LANGUAGE_NOT_VALID: "Language value is not valid",
  VISIBILITY_NOT_VALID: "visibility value is not valid",
  GAME_TYPE_NOT_VALID: "Game type is not valid",
  EXECUTION_MODE_NOT_VALID: "Execution mode is not valid",
  SCORING_NOT_VALID: "Scoring value is not valid",
  PLAYER_TYPE_NOT_VALID: "Player type is not valid",


  // Pagination Value

  SEARCH_CONTEST_PAGE_SIZE: 10,

  STATUS: {
    ACTIVE: 1,
    PENDING: 0,
  },
  CONTEST_CODES: {
    LANGUAGE: {
      ENGLISH: 1,
      HINDI: 2,
      GUJARATI: 3,
      MARATHI: 4,
      TAMIL: 5,
      PUNJABI: 6,
      SPANISH: 7,
      BHOJPURI: 8,
      TELUGU: 9,
      OTHER: 10
    },
  },

  RENDERING_MODE:{
    Automatic:1,
    OnClick:2
  },
  GAME_TYPES: {
    Hangman: 1,
    Unscramble: 2,
    Bingo: 3,
    Quiz: 4,
    MatchIt: 5,
    GuessAndGo: 6,
    Gibberish: 7,
    Taboo: 8,
    Blank: 9,
  },

  CATEGORY_LABEL: {
    General: 1,
    Entertainment: 2,
    Business: 3,
    Sports: 4,
    ArtAndDesign: 5,
    LatestInMurabbo: 6,
    Food: 7,
    History: 8,
    International: 9,
    NatureAndLife: 10,
    Kids: 11,
    Fitness: 12,
    Religion: 13,
    Technology: 14,
    Cars: 15,
    TravelAndLeisure: 16,
    Education: 17
  },


  CATEGORY_LABEL_DISPLAY: {
    1: "General",
    2: "Entertainment",
    3: "Business",
    4: "Sports",
    5: "Art & Design",
    6: "Latest In Murabbo",
    7: "Food",
    8: "History",
    9: "International",
    10: "Nature & Life",
    11: "Kids",
    12: "Fitness",
    13: "Religion",
    14: "Technology",
    15: "Cars",
    16: "Travel & Leisure",
    17: "Education"
  },



  EXECUTION_MODE: {
    Assigned: 1,
    Competitive: 2,
  },
  SCORING: {
    Manual: 1,
    Automatic: 2,
  },
  VISIBILITY: {
    Private: 1,
    Public: 2,
  },
  playerType: {
    singlePlayer: 1,
    multiPlayer: 2,
  },
  ANSWER_TYPE: {
    single: 1,
    multiple: 2,
    freeText: 3,
    flashCard: 4,
    boolean: 1
  },
  ANSWER_HINT: {
    noHint: 1,
    always: 2,
    onDemand: 3,
  },
  CORRECT_ANSWER: {
    correct: 1,
    incorrect: 2,
  },


};
